lastidx = '% s+% dc' % (8, 8)
print(lastidx)

a={'Afrikaans':'af',
 'Irish':'ga',
 'Albanian':'sq',
 'Italian':'it',
 'Arabic':'ar',
'Japanese':'ja',
'Azerbaijani':'az',
'Kannada':'kn',
'Basque':'eu',
'Korean':'ko',
'Bengali':'bn',
'Latin':'la',
'Belarusian':'be',
'Latvian':'lv',
'Bulgarian':'bg',
'Lithuanian':'lt',
'Catalan':'ca',
'Macedonian':'mk',
'Chinese Simplified':'zh-CN',
'Malay':'ms',
'Chinese Traditional':'zh-TW',
'Maltese':'mt',
'Croatian':'hr',
'Norwegian  ':'no',
'Czech':'cs',
'Persian':'fa',
'Danish':'da',
'Polish':'pl',
'Dutch':'nl',
'Portuguese':'pt',
'English':'en',
'Romanian':'ro',
'Esperanto':'eo',
'Russian':'ru',
'Estonian':'et',
'Serbian':'sr',
'Filipino':'tl',
'Slovak':'sk',
'Finnish':'fi',
'Slovenian':'sl',
'French':'fr',
'Spanish':'es',
'Galician':'gl',
'Swahili':'sw',
'Georgian':'ka',
'Swedish':'sv',
'German	':'de',
'Tamil':'ta',
'Greek':'el',
'Telugu':'te',
'Gujarati':'gu',
'Thai':'th',
'Haitian Creole':'ht',
'Turkish':'tr',
'Hebrew':'iw',
'Ukrainian':'uk',
'Hindi':'hi', 
'Urdu':'ur',
'Hungarian':'hu',
'Vietnamese':'vi',
'Icelandic':'is',
'Welsh':'cy',
'Indonesian':'id',
'Yiddish':'yi',}
print(a)
for i in a:
    print(i)
LANGUAGES = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'az': 'azerbaijani',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'ceb': 'cebuano',
    'ny': 'chichewa',
    'zh-cn': 'chinese (simplified)',
    'zh-tw': 'chinese (traditional)',
    'co': 'corsican',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'gl': 'galician',
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'haw': 'hawaiian',
    'iw': 'hebrew',
    'he': 'hebrew',
    'hi': 'hindi',
    'hmn': 'hmong',
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jw': 'javanese',
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'ko': 'korean',
    'ku': 'kurdish (kurmanji)',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mn': 'mongolian',
    'my': 'myanmar (burmese)',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'gd': 'scots gaelic',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
    'sd': 'sindhi',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'sv': 'swedish',
    'tg': 'tajik',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'vi': 'vietnamese',
    'cy': 'welsh',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu',}
print(LANGUAGES)
    
